all:
	libtoolize --copy --force
	aclocal --verbose
	autoheader
	automake --add-missing --copy --include-deps --foreign --gnu --verbose
	autoconf
	@echo System ready for compilation. Now run ./configure and make to build XFce
