/*  xfumed
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/

#ifndef _USER_MENU_H
#define _USER_MENU_H

#include <glib.h>
#include <gtk/gtk.h>
#include <stdio.h>
#include <string.h>

#include "xfumed.h"

#define INTROTEXT _("# This file was generated by xfumed - XFce User Menu Editor")

/* Prototypes */
RootMenu *menu_new (gchar * name);

RootMenu *menu_find_by_name (gchar * name);

gchar *menu_get_caption (RootMenu * menu);

gint compare_menuname (gpointer * menu, gpointer * name);

GList *menu_add (RootMenu * menu);

GList *menu_remove (RootMenu * menu);


ItemData *item_new (void);

ItemData *item_nth (RootMenu * menu, gint n);

void item_add (RootMenu * menu, ItemData * item);

void item_update_nth (RootMenu * menu, ItemData * item, gint n);

void item_remove_nth (RootMenu * menu, gint n);


GList *clear_menulist ();

void read_menu ();

gint get_line (FILE * fp, gchar line[], gint limit);

gchar *get_eol (gchar * text);

gchar *get_next_word (gchar * text);

ItemData *item_from_menuline (gchar * line);

void write_menu ();

#endif
