/* ctree icons */
#ifndef __ICONS_H__
#define __ICONS_H__
#include "icons/page.xpm"
#include "icons/page_html.xpm"
#include "icons/page_lnk.xpm"
#include "icons/dir_close.xpm"
#include "icons/dir_pd.xpm"
#include "icons/dir_close_lnk.xpm"
#include "icons/dir_open.xpm"
#include "icons/dir_open_lnk.xpm"
#include "icons/dir_up.xpm"
#include "icons/exe.xpm"
#include "icons/exe_script.xpm"
#include "icons/exe_lnk.xpm"
#include "icons/char_dev.xpm"
#include "icons/fifo.xpm"
#include "icons/socket.xpm"
#include "icons/block_dev.xpm"
#include "icons/stale_lnk.xpm"
#include "icons/xftree_icon.xpm"
#include "icons/tar.xpm"
#include "icons/compressed.xpm"
#include "icons/text.xpm"
#include "icons/image.xpm"
#include "icons/page_audio.xpm"
#endif
