/* Automatically generated by po2tbl.sed from xfce.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Select Color", 2},
  {"Select File", 3},
  {"Font Selection", 4},
  {"OK", 5},
  {"Message", 6},
  {"Yes", 7},
  {"No", 8},
  {"Question", 9},
  {"Terminated: ", 10},
  {"*** WARNING ***: Cannot load image file %s\n", 11},
  {"*** WARNING ***: Cannot load pixmap file %s\n", 12},
  {"Define action ...", 13},
  {"Command Line :", 14},
  {"Icon Style :", 15},
  {"Browse ...", 16},
  {"Ok", 17},
  {"Cancel", 18},
  {"You must provide the command to execute !", 19},
  {"\
XFce : Syntax error in configuration file\n\
(%s)\n", 20},
  {"\
Syntax error in configuration file\n\
Aborting", 21},
  {"\
XFce : Data mismatch error in config file\n\
(%s)\n", 22},
  {"\
Data mismatch error in configuration file\n\
Aborting", 23},
  {"Cannot create file", 24},
  {"Cannot reset configuration file", 25},
  {"Creating new config file...\n", 26},
  {"Cannot open configuration file", 27},
  {"Does not looks like an XFce 3 configuration file !", 28},
  {"\
Do you want to reset the configuration file ?\n\
 \t(The previous file will be saved with a \".orig\" extension)", 29},
  {"Cannot open new config, Giving up...", 30},
  {"Cannot load configuration file", 31},
  {"Cannot use old version of XFce configuration files", 32},
  {"Subprocess diagnostic", 33},
  {"Clear", 34},
  {"Dismiss", 35},
  {"Info ...", 36},
  {"Couldn't create pixmap", 37},
  {"By Olivier Fourdan (c) 1997-2000", 38},
  {"Accept", 39},
  {"Modify Item ...", 40},
  {"Preview Icon", 41},
  {"Icon File :", 42},
  {"Label :", 43},
  {"Position :", 44},
  {"Remove", 45},
  {"Add Item ...", 46},
  {"Are you sure you want to remove this entry ?", 47},
  {"\
You must provide the command\n\
and the label, at least !", 48},
  {"Add a new entry...", 49},
  {"Add icon...", 50},
  {"Click to tear off popup menu", 51},
  {"Cannot find the file you dropped !", 52},
  {"Screen label ...", 53},
  {"Define screen label :", 54},
  {"Files related", 55},
  {"Terminals/Connections", 56},
  {"Mail tools/browsers", 57},
  {"Print manager", 58},
  {"Configuration", 59},
  {"Misc. tools/Utilities", 60},
  {"Manual/Help browser", 61},
  {"Writing/Text tools", 62},
  {"Schedule/Appointments", 63},
  {"Multimedia", 64},
  {"Games", 65},
  {"Network", 66},
  {"Sound", 67},
  {"External...", 68},
  {"Setup", 69},
  {"GTK theme engine : ", 70},
  {"Apply colors to all applications", 71},
  {"Load ...", 72},
  {"Save ...", 73},
  {"Default", 74},
  {"Repaint root window of workspace", 75},
  {"Use gradient color as wallpaper", 76},
  {"Use tear-off menus", 77},
  {"Show subprocess diagnostic dialog", 78},
  {"Panel layer", 79},
  {"Bottom", 80},
  {"Top", 81},
  {"Clock", 82},
  {"Use digital clock on panel", 83},
  {"Use military time (24 hours)", 84},
  {"Tooltips", 85},
  {"Tooltips delay (ms.) : ", 86},
  {"Virtual Screens", 87},
  {"Number of virtual desktops : ", 88},
  {"Popups & Icons", 89},
  {"Number of popup menus : ", 90},
  {"Size of icons on panel", 91},
  {"Large", 92},
  {"Medium", 93},
  {"Small", 94},
  {"Size of icons on pop-up menus", 95},
  {"Font style", 96},
  {"Browse...", 97},
  {"Click to focus windows", 98},
  {"Automatically focus on new window", 99},
  {"Auto raise windows", 100},
  {"Show contents of window while moving", 101},
  {"Show contents of window while resizing", 102},
  {"Use gradient color for the active window", 103},
  {"Use gradient color for inactive windows", 104},
  {"Window border style : ", 105},
  {"Window snapping size (0 disable) : ", 106},
  {"Icon position", 107},
  {"Left", 108},
  {"bottom", 109},
  {"Right", 110},
  {"Title font :", 111},
  {"Icon font :", 112},
  {"Menu font :", 113},
  {"Sound module (xfsound)", 114},
  {"Mouse settings (xfmouse)", 115},
  {"Backdrop settings (xfbd)", 116},
  {"Pager (xfpager)", 117},
  {"GNOME (xfgnome)", 118},
  {"GNOME menu (xfmenu)", 119},
  {"KDE menu (xfmenu)", 120},
  {"Palette", 121},
  {"XFce", 122},
  {"Windows", 123},
  {"Startup", 124},
  {"Apply", 125},
  {"Please wait, XFce is loading...", 126},
  {"One", 127},
  {"Two", 128},
  {"Three", 129},
  {"Four", 130},
  {"Five", 131},
  {"Six", 132},
  {"Seven", 133},
  {"Eight", 134},
  {"Nine", 135},
  {"Ten", 136},
  {"Eleven", 137},
  {"Twelve", 138},
  {"Thirteen", 139},
  {"Fourteen", 140},
  {"Fifteen", 141},
  {"Sixteen", 142},
  {"Seventeen", 143},
  {"Eighteen", 144},
  {"Nineteen", 145},
  {"Twenty", 146},
  {"Digital mode", 147},
  {"24 hours mode", 148},
  {"About...", 149},
  {"Setup...", 150},
  {"Quit", 151},
  {"Sunday", 152},
  {"Monday", 153},
  {"Tuesday", 154},
  {"Wednesday", 155},
  {"Thursday", 156},
  {"Friday", 157},
  {"Saturday", 158},
  {"January", 159},
  {"February", 160},
  {"March", 161},
  {"April", 162},
  {"May", 163},
  {"June", 164},
  {"July", 165},
  {"August", 166},
  {"September", 167},
  {"October", 168},
  {"November", 169},
  {"December", 170},
  {"\
Are you sure you want to Quit ?\n\
This might log you off !", 171},
  {"\
You've selected a desktop which is not currently\n\
visible in XFce panel.", 172},
  {"XFCE: Communication pipe closed. Exiting...\n", 173},
  {"Workspace", 174},
  {"_Ok", 175},
  {"_Yes", 176},
  {"_Continue", 177},
  {"Skip", 178},
  {"_Cancel", 179},
  {"_No", 180},
  {"_All", 181},
  {"_Close", 182},
  {"Open with ...", 183},
  {"Run program ...", 184},
  {"Open in terminal", 185},
  {"Remember application", 186},
  {"Fatal error in %s at %d\n", 187},
  {"Source : ", 188},
  {"Target : ", 189},
  {"0 bytes received", 190},
  {"XFTree: Download", 191},
  {"%d bytes received (%d bps)", 192},
  {"Properties", 193},
  {"All", 194},
  {"Info", 195},
  {"Name :", 196},
  {"Type :", 197},
  {"%lld Bytes", 198},
  {"Size :", 199},
  {"Creation Time :", 200},
  {"Modification Time :", 201},
  {"Access Time :", 202},
  {"Permissions", 203},
  {"Owner :", 204},
  {"Read", 205},
  {"Write", 206},
  {"Execute", 207},
  {"Set UID", 208},
  {"Group :", 209},
  {"Set GID", 210},
  {"Other :", 211},
  {"Sticky", 212},
  {"Owner", 213},
  {"unknown", 214},
  {"Can't find suffix in filename, using complete filename", 215},
  {"Register program for file \"%s\"", 216},
  {"Register program for suffix \"%s\"", 217},
  {"XFTree, based on XTree Version %s\n", 218},
  {"directory: %s\n", 219},
  {"creating directory: %s\n", 220},
  {"geometry: %dx%d+%d+%d\n", 221},
  {"Insufficient system memory", 222},
  {"Too few bytes transferred ! Device full ?", 223},
  {"Too many bytes transferred !?", 224},
  {"Can't stat() file", 225},
  {"Error closing file", 226},
  {"Error deleting", 227},
  {"Can't copy FIFO", 228},
  {"Can't copy device file", 229},
  {"Can't copy socket", 230},
  {"Counting files", 231},
  {"%d / %d", 232},
  {"Source: ", 233},
  {"Target: ", 234},
  {"file x of x", 235},
  {"XFTree: Copy", 236},
  {"XFTree: Move", 237},
  {"XFTree: Link", 238},
  {"Unknown action !", 239},
  {"URL type not yet enabled", 240},
  {"Disk usage:", 241},
  {"No directory selected !", 242},
  {"Cannot find path", 243},
  {"Go to", 244},
  {"Open in new", 245},
  {"New Folder", 246},
  {"New file", 247},
  {"Delete ...", 248},
  {"Insert from pasteboard", 249},
  {"Find ...", 250},
  {"Show disk usage ...", 251},
  {"Cut to pasteboard", 252},
  {"Copy to pasteboard", 253},
  {"List pasteboard contents", 254},
  {"Clear pasteboard", 255},
  {"Select all", 256},
  {"Unselect", 257},
  {"Toggle Dotfiles", 258},
  {"Open Trash", 259},
  {"Empty Trash", 260},
  {"Duplicate", 261},
  {"Rename ...", 262},
  {"Properties ...", 263},
  {"Go to ...", 264},
  {"Register ...", 265},
  {"Go home", 266},
  {"Go back", 267},
  {"Go up", 268},
  {"Update", 269},
  {"Differences ...", 270},
  {"Patch viewer ...", 271},
  {"Close window", 272},
  {"Quit ...", 273},
  {"Subsort by file type", 274},
  {"Enable filter", 275},
  {"Abbreviate paths", 276},
  {"Status box", 277},
  {"Status titles", 278},
  {"Short titles", 279},
  {"Hide toolbar", 280},
  {"Hide titles", 281},
  {"Hide dates", 282},
  {"Hide sizes", 283},
  {"Sort by file name", 284},
  {"Sort by file size", 285},
  {"Sort by file date", 286},
  {"File", 287},
  {"Edit", 288},
  {"Tools", 289},
  {"View", 290},
  {"Preferences", 291},
  {"Hide main menu", 292},
  {"Save geometry on exit", 293},
  {"Double click does GOTO", 294},
  {"Drag does copy", 295},
  {"Set background color", 296},
  {"Set font", 297},
  {"Configure toolbar", 298},
  {"Redefine home directory", 299},
  {"Help", 300},
  {"Drag and drop", 301},
  {"Unlisted shortcut keys", 302},
  {"Custom shortcut keys", 303},
  {"Registered applications", 304},
  {"About ...", 305},
  {"Name", 306},
  {"Size (bytes)", 307},
  {"Last changed", 308},
  {"Filter:", 309},
  {"dirs", 310},
  {"files", 311},
  {"Show main menu", 312},
  {"Could not load specified font\n", 313},
  {"Override ?", 314},
  {"with", 315},
  {"Default xftreerc file cannot be created\n", 316},
  {"Default xftreerc file cannot be read\n", 317},
  {"\
Xftree handles keyboard shortcuts dynamically.\n\
This means that you can open a menu,highlight an entry\n\
and press a keyboard key to create the shortcut.", 318},
  {"\
Xftree can register applications by filename or filetype\n\
by selecting \"Register\" from one of the menus or by selecting\n\
\"Register application\" on mouse double-click.\n\
If you wish to edit the applications that are already registered,\n\
 please look at ~/.xfce/xtree.reg.", 319},
  {"\
Xftree handles drag and drop the following way:\n\
SHIFT drag+drop --> move\n\
CTRL drag+drop --> copy\n\
SHIFT-CTRL drag+drop --> link\n\
The default drag+drop action is move,\n\
but can be changed in the preferences menu.\n\
To drag multiple files, use the middle button.\n", 320},
  {"Keyboard shortcuts are a fast way to access menu functions.", 321},
  {"Xftree results", 322},
  {"Home directory : ", 323},
  {"Cannot create pasteboard\n", 324},
  {"Please select exactly one directory to insert the pasteboard contents.", 325},
  {"The pasteboard is currently empty.", 326},
  {"Pasteboard contents:\n", 327},
  {"Strip level now set to ", 328},
  {"No patch file has been selected.", 329},
  {"No directory to apply patch has been selected.", 330},
  {"No left path has been selected.", 331},
  {"No right path has been selected.", 332},
  {"Patch file can not be opened for read!", 333},
  {"\
Files are identical\n\
(or binary files that may or may not differ)", 334},
  {"Patch file is not in unified format", 335},
  {"****Empty file****\n", 336},
  {"****Binary data****\n", 337},
  {"\
You have selected a directory.\n\
Should subdirectories be included?", 338},
  {" versus ", 339},
  {"different sections found", 340},
  {"Include binary files?", 341},
  {"Include subdirectories?", 342},
  {"Working diff...\n", 343},
  {"\
Patch file has been modified by another process\n\
Please reload\n", 344},
  {"Reversed patch detected. Should I try reversing it?", 345},
  {"Now forking diff. Please be patient.\n", 346},
  {"Finished forking.\n", 347},
  {"Running patch...\n", 348},
  {"xfdiff version", 349},
  {"use xfdiff [ -h | --help | -p] [leftfile] [rightfile]\n", 350},
  {"-p : leftfile and rightfile are a patchdir and a patchfile\n", 351},
  {"-PN: N is strip level (0-9) for patch (quick toggle)\n", 352},
  {"-R: patch file is reversed (quick toggle)\n", 353},
  {"-N: patch file is not reversed (quick toggle)\n", 354},
  {"\
-h, --help : print this message\n\
\n", 355},
  {"xfdiff (c) Edscott Wilson Garcia 2001, under GNU-GPL\n", 356},
  {"\
XFCE modules copyright Olivier Fourdan 1999-2001, under GNU-GPL\n\
\n", 357},
  {"Xfdiff diagnostic", 358},
  {"A patch file and directory must be selected first!", 359},
  {"Patch has been undone.", 360},
  {"Patch has been applied.", 361},
  {"Please select a name for the patch file in the next dialog.", 362},
  {"\
XFdiff will now start diff.\n\
Please be patient (xfdiff might seem to hang).\n\
Diff will be working", 363},
  {"Patch file could not be created", 364},
  {"Strip level for created patch file=", 365},
  {" has been created\n", 366},
  {"Patch file creation cancelled", 367},
  {"Line synchronization enabled.\n", 368},
  {"Line synchronization disabled.\n", 369},
  {"Patch verbose diagnostics enabled.\n", 370},
  {"Patch verbose diagnostics disabled.\n", 371},
  {"Line numbers enabled.\n", 372},
  {"Line numbers disabled.\n", 373},
  {"Polygons will now be filled.\n", 374},
  {"Polygons will now *not* be filled.\n", 375},
  {"Patch will now be assumed reversed.\n", 376},
  {"Patch will now be assumed *not* reversed.\n", 377},
  {"Font selection", 378},
  {"Select highlight background color", 379},
  {"Select highlight text color", 380},
  {"Warning: cannot read from ", 381},
  {"is not in patch file.", 382},
  {"Default .xfdiffrc file cannot be created\n", 383},
  {"Default configuration has been saved\n", 384},
  {"This is XFDiff ", 385},
  {"\
\n\
(c) by Edscott Wilson Garcia under GNU GPL\n\
XFCE modules (c) Olivier Fourdan http://www.xfce.org/", 386},
  {"There is no next difference", 387},
  {"There is no previous difference", 388},
  {"There is no such file", 389},
  {"There is no next file", 390},
  {"There is no previous file", 391},
  {"That is a directory (or symlink)", 392},
  {"Select left file", 393},
  {"Select right file", 394},
  {"Select patch file", 395},
  {"Select directory where to apply patch", 396},
  {"Switch to patch mode", 397},
  {"Switch to diff mode", 398},
  {"Exit", 399},
  {"Diff Settings", 400},
  {"Font", 401},
  {"Highlight text color", 402},
  {"Highlight background color", 403},
  {"Fill polygons", 404},
  {"Show line numbers", 405},
  {"Use line synchronization voids", 406},
  {"Save settings as default", 407},
  {"Patch Settings", 408},
  {"Verbose patch diagnostics", 409},
  {"Patch options only active in patch-mode", 410},
  {"Assume patch is reversed", 411},
  {"Auto strip level", 412},
  {"Actions", 413},
  {"View differences", 414},
  {"View differences in new", 415},
  {"View patch created differences", 416},
  {"View patch created differences in new", 417},
  {"Create patch file", 418},
  {"Apply patch to Hard Drive", 419},
  {"Undo patch to Hard Drive", 420},
  {"About", 421},
  {"Next difference", 422},
  {"Prev difference", 423},
  {"Next file", 424},
  {"Previous file", 425},
  {"Could not set selected font", 426},
  {"Confirm", 427},
  {"Abort", 428},
  {"Alert", 429},
  {"\
A bug?\n\
Please send full traceback to xfce-dev@moongroup.com", 430},
  {"Low memory (malloc) error: xfdiff_aborting run", 431},
  {"file open error: xfdiff_aborting run", 432},
  {"unspecified error: xfdiff_aborting run", 433},
  {"\
No file was found for patching\n\
Either the directory to apply patch is not correctly selected\n\
or an incorrect strip level was used.\n", 434},
  {"\
Patch command has produced reject output.\n\
See diagnostics window.", 435},
  {"No directory was selected!", 436},
  {"Directory or file selection", 437},
  {"Please select it in the next dialog.", 438},
  {"File exists, overwrite?", 439},
  {"Cannot open file for write\n", 440},
  {"couldn't allocate color", 441},
  {"Patch: ", 442},
  {" applied at: ", 443},
  {"Press OK to see patch diffs", 444},
  {"Results limit reached", 445},
  {"Cancelled", 446},
  {"Search canceled!\n", 447},
  {"Glob run must finish or be cancelled first.", 448},
  {"Find results.\n", 449},
  {"Find results...", 450},
  {"Directory", 451},
  {"Mode", 452},
  {"Incoherent size considerations!", 453},
  {"Result of ", 454},
  {"File type :", 455},
  {"Anyone", 456},
  {"Any kind", 457},
  {"Regular", 458},
  {"Symlink", 459},
  {"Socket", 460},
  {"Block device", 461},
  {"Character device", 462},
  {"FIFO", 463},
  {"Xfglob", 464},
  {"Find", 465},
  {"Path : ", 466},
  {"Browse", 467},
  {"File filter : ", 468},
  {"What's a file filter?", 469},
  {"\
Basic rules:\n\
\n\
*  Will match any character zero or more times.\n\
?  Will match any character exactly one time\n", 470},
  {"Search subdirectories too", 471},
  {"Limit results to first : ", 472},
  {"Content search", 473},
  {"Containing : ", 474},
  {"Case sensitive search", 475},
  {"Extended regexp", 476},
  {"What's a regexp?", 477},
  {"\
Reserved characters for extended regexp are\n\
. ^ $ [ ] ? * + { } | \\ ( ) : \n\
In  basic regular expressions the metacharacters\n\
?, +, {, |, (, and ) lose their special meaning.\n\
\n\
The  period  .   matches  any  single  character.\n\
The caret ^ matches at the start of line.\n\
The dollar $ matches at the end of line.\n\
\n\
Characters within [ ] matches any single \n\
       character in the list.\n\
Characters within [^ ] matches any single\n\
       character *not* in the list.\n\
Characters inside [ - ] matches a range of\n\
       characters (ie [0-9] or [a-z]).\n\
\n\
A regular expression may be followed by one\n\
       of several repetition operators:\n\
?      The preceding item is optional and matched\n\
       at most once.\n\
*      The preceding item will be matched zero\n\
       or more times.\n\
+      The preceding item will be matched one or\n\
       more times.\n\
{n}    The preceding item is matched exactly n times.\n\
{n,}   The preceding item is matched n or more times.\n\
{n,m}  The preceding item is matched at least n times,\n\
       but not more than m times.\n\
\n\
To match any reserved character, precede it with \\. \n\
\n\
Two regular expressions may be joined by the logical or\n\
       operator |.\n\
Two regular expressions may be concatenated.\n\
\n\
More information is available by typing \"man grep\"\n\
       at the command prompt.\n", 478},
  {"File considerations", 479},
  {"Stay on single filesystem", 480},
  {"What's a single filesystem?", 481},
  {"\
Staying on a single filesystem will hinder\n\
searching on different physical disk partitions.\n\
This is especially useful if you do not want\n\
to search into nfs or smb mounts.\n", 482},
  {"Permission considerations", 483},
  {"How does permission filtering work?", 484},
  {"\
When permission filtering is active:\n\
-If a file has one of the chosen permission bits,\n\
  it will match.\n\
-If no permission bit is chosen, files with \n\
  no set permission bits will match.\n", 485},
  {"User/group considerations", 486},
  {"How does user/group filtering work?", 487},
  {"\
If user and group are both set to any \n\
value other than anyone:\n\
-files must meet both criteria in order\n\
  to match\n", 488},
  {"User ID: ", 489},
  {"Group ID: ", 490},
  {"Size considerations", 491},
  {"How does size filtering work?", 492},
  {"\
-If a size of 0 (zero) is specified for \n\
 size-less-than, this will be ignored.\n\
-If both size-greater-than and size-less-than\n\
 are specified, both criteria must be met\n\
 in order for a file to match.\n", 493},
  {"Size greater than (KB): ", 494},
  {"Size less than (KB): ", 495},
  {"Time considerations", 496},
  {"How does time filtering work?", 497},
  {"\
Three different time modes may be selected:\n\
*modified:\n\
  This changes when the file is modified, e.g.\n\
  by mknod(2), truncate(2), utime(2) and write(2)\n\
 (of  more than  zero  bytes). Moreover, modification\n\
  time of a directory is changed by the creation or \n\
  deletion of  files  in  that directory. Modification\n\
  time is not changed for changes in owner, group,\n\
  hard link count, or mode.\n\
\n\
*changed:\n\
  This field is changed by writing or setting inode\n\
  information (i.e., owner, group, link count, mode).\n\
\n\
*accessed:\n\
  This field is changed by file accesses, e.g. by\n\
  exec(2), mknod(2), pipe(2), utime(2) and read(2)\n\
  (of more than zero bytes). Other routines, like\n\
  mmap(2), may or may not update access time.\n\
\n\
Please note: after filtering a file through glob, it\n\
will have its access time altered, so two consecutive\n\
runs will not produce identical results.\n", 498},
  {"Modified", 499},
  {"Changed", 500},
  {"Accessed", 501},
  {"In the previous : ", 502},
  {"Minutes", 503},
  {"Hours", 504},
  {"Days", 505},
  {"Months", 506},
  {"General considerations", 507},
  {"Do not look into binary files", 508},
  {"Output count of matching lines", 509},
  {"Match anywhere", 510},
  {"Match whole words only", 511},
  {"Match whole lines only", 512},
  {"Output files where no match is found", 513},
  {"Filter options", 514},
  {"Content options", 515},
  {"Results", 516},
  {"working...", 517},
  {"Cancel Search", 518},
  {"Nothing found...\n", 519},
  {"Files found=", 520},
  {"(interrupted because limit exceded)", 521},
  {"lines", 522},
  {"unable to stat:", 523},
  {"XFClock - XFce Clock & Calendar", 524},
  {"\
XFClock\n\
(c) 1997-2000 Olivier Fourdan", 525},
  {"\
XFclock : Syntax error in configuration file\n\
(%s)\n", 526},
  {"\
XFclock : Data mismatch error in config file\n\
(%s)\n", 527},
  {"Hide/show menubar", 528},
  {"Hide/show calendar", 529},
  {"Settings", 530},
  {"24 hour mode", 531},
  {"Display AM/PM", 532},
  {"Display seconds", 533},
  {"Background color...", 534},
  {"Foreground color...", 535},
  {"Font...", 536},
  {"Hide menubar", 537},
  {"Calendar Options", 538},
  {"Mark Fridays", 539},
  {"Mark Saturdays", 540},
  {"Mark Sundays", 541},
  {"Show week numbers", 542},
  {"Show day names", 543},
  {"Show heading", 544},
  {"Week starts on Monday", 545},
  {"xfmouse: Error, cannot open display.\n", 546},
  {"Is X running and $DISPLAY correctly set ?\n", 547},
  {"XFMouse - XFce Mouse Configuration", 548},
  {"Button Settings", 549},
  {"Motion Settings", 550},
  {"Threshold : ", 551},
  {"Acceleration : ", 552},
  {"Usage : %s [OPTIONS]\n", 553},
  {"   Where OPTIONS are :\n", 554},
  {"   -i : interactive\n", 555},
  {"\
   -d : apply configuration and exit (default)\n\
\n", 556},
  {"\
%s is part of the XFce distribution, written by Olivier Fourdan\n\
\n", 557},
  {"New Desk", 558},
  {"Add Window", 559},
  {"Raise Window", 560},
  {"Lower Window", 561},
  {"Configure Window", 562},
  {"Focus Change", 563},
  {"Destroy Window", 564},
  {"Iconify", 565},
  {"De-iconify", 566},
  {"Shade", 567},
  {"Un-Shade", 568},
  {"Maximize", 569},
  {"De-maximize", 570},
  {"Shutdown", 571},
  {"Unknown", 572},
  {"XFSound - XFce Sound Manager", 573},
  {"Event : ", 574},
  {"Sound file : ", 575},
  {"Test", 576},
  {"Play Sound", 577},
  {"Command : ", 578},
  {"Internal", 579},
  {"External", 580},
  {"\
Error\n\
Cannot open file", 581},
  {"\
Error\n\
Cannot allocate colors", 582},
  {"\
Error\n\
File format invalid", 583},
  {"\
Error\n\
Color definition invalid", 584},
  {"\
Error\n\
Not enough Memory", 585},
  {"XFbd - XFce Backdrop Manager", 586},
  {"Filename : ", 587},
  {"Display image : ", 588},
  {"Tiled", 589},
  {"Stretched", 590},
  {"Auto", 591},
  {"   -i : interactive, prompts for backdrop to display\n", 592},
  {"\
   -d : display, reads configuration and exit (default)\n\
\n", 593},
  {"xfbdmgr - XFCE List Manager", 594},
  {"File not found.\n", 595},
  {"&Restart", 596},
  {"&Quit", 597},
  {"&Move", 598},
  {"&Resize", 599},
  {"(De)&Iconify", 600},
  {"(Un)&Stick", 601},
  {"(Un)S&hade", 602},
  {"(Un)Ma&ximize", 603},
  {"Se&nd to...", 604},
  {"S&witch to...", 605},
  {"&Close", 606},
  {"User Menu", 607},
  {"Edit menu...", 608},
  {"&Mouse...", 609},
  {"&Backdrop...", 610},
  {"&Sound...", 611},
  {"&New window", 612},
  {"&User Menu", 613},
  {"&Arrange icons", 614},
  {"&Iconify all", 615},
  {"&Refresh", 616},
  {"Shuffle &Up", 617},
  {"Shuffle &Down", 618},
  {"&Settings", 619},
  {"&Quit XFwm", 620},
  {"&Full Screen", 621},
  {"&Vertical", 622},
  {"&Horizontal", 623},
  {"xfwm terminated: ", 624},
  {"Samba failure! Xfsamba could not find file:", 625},
  {"(please install Samba or else correct the PATH environment variable)", 626},
  {"File download failed. See diagnostics for reason.", 627},
  {"Download done.", 628},
  {"Downloading file...", 629},
  {"File download cancelled.", 630},
  {"Download failed.", 631},
  {"\
If you have win95 nodes on your network, xfsamba might not find\n\
a master browser. If you start smb services on your linux box,\n\
making it a samba-server, the problem will be fixed as long as\n\
the win95 box(es) are reset. You know the routine, reset wind*ws\n\
for changes to take effect. Otherwise,\n\
you must type in the node to be browsed and hit RETURN.\n", 632},
  {"This is XFSamba ", 633},
  {"\
\n\
(c) Edscott Wilson Garcia under GNU GPL\n\
XFCE modules are (c) Olivier Fourdan http://www.xfce.org/", 634},
  {"Please provide information for server ", 635},
  {"Please provide browsing preferences ", 636},
  {"Username : ", 637},
  {"Password  : ", 638},
  {"A file must be selected!", 639},
  {"A directory must be selected!", 640},
  {"Something to be deleted must be selected!", 641},
  {"Going to master browser...", 642},
  {"Going back...", 643},
  {"Going forward...", 644},
  {"Attempting to stop query...", 645},
  {"Query stopped.", 646},
  {"Download...", 647},
  {"Upload...", 648},
  {"New folder...", 649},
  {"Delete...", 650},
  {"Tar...", 651},
  {"Browse as...", 652},
  {"Show diagnostics", 653},
  {"Hide diagnostics", 654},
  {"Show browser links", 655},
  {"Hide browser links", 656},
  {"Go", 657},
  {"Home...", 658},
  {"Reload...", 659},
  {"Forward...", 660},
  {"Back...", 661},
  {"About master browser...", 662},
  {"About xfsamba...", 663},
  {"Back ...", 664},
  {"Forward ...", 665},
  {"Reload ...", 666},
  {"Home ...", 667},
  {"Stop ...", 668},
  {"New folder ...", 669},
  {"Download ...", 670},
  {"Upload ...", 671},
  {"Tar ...", 672},
  {"Help ...", 673},
  {"Set View 3", 674},
  {"Set View 2", 675},
  {"Set View 1", 676},
  {"Location : ", 677},
  {"Show IP", 678},
  {"Location shares : ", 679},
  {"Size", 680},
  {"Date", 681},
  {"Comment", 682},
  {"Location known servers : ", 683},
  {"Location known workgroups : ", 684},
  {"Welcome to xfsamba.", 685},
  {"Retrieve done.", 686},
  {"Query password has been requested.", 687},
  {"List failed.", 688},
  {"Retreiving...", 689},
  {"Resolved", 690},
  {"Resolving for", 691},
  {"Shares", 692},
  {"Links to other servers", 693},
  {"Links to other workgroups", 694},
  {"Query done.", 695},
  {"Query failed. Machine may be down.", 696},
  {"Querying", 697},
  {"No master browser found. See diagnostics.", 698},
  {"\
No master browser found.\n\
Please type a computer name at location and hit RETURN", 699},
  {"Looking for master browsers...", 700},
  {"Please provide netbios name for master browser at ", 701},
  {"Master browser netbios name must be provided.", 702},
  {"No status response", 703},
  {"Master browser not resolved. Use location box to browse.", 704},
  {"\
No master browser resolved.\n\
Please type a computer name at location and hit RETURN", 705},
  {"Resolving", 706},
  {"Please provide a name for the new directory at", 707},
  {"Directory creation failed. See diagnostics for details.", 708},
  {"Directory created.", 709},
  {"Create directory cancelled.", 710},
  {"Create directory failed.", 711},
  {"Creating dir...", 712},
  {"Remove failed. See diagnostics for details.", 713},
  {"Remove complete.", 714},
  {"Removing...", 715},
  {"Sorry, top level shares cannot be removed.", 716},
  {"Remove cancelled.", 717},
  {"Confirm remove?", 718},
  {"Tar failed. See diagnostics for details.", 719},
  {"Tar extraction has completed", 720},
  {"Tar command complete.", 721},
  {"Please select input tarfile next.", 722},
  {"Please select the output tarfile next.", 723},
  {"Tar cancelled.", 724},
  {"Cannot open tar file", 725},
  {"Cannot create tar file", 726},
  {"create", 727},
  {"extract", 728},
  {"full", 729},
  {"incremental", 730},
  {"do not reset archive bit", 731},
  {"reset archive bit", 732},
  {"Options", 733},
  {"File upload failed. See diagnostics for reason.", 734},
  {"Upload done.", 735},
  {"Uploaded file.", 736},
  {"Uploading file...", 737},
  {"File upload cancelled.", 738},
  {"Specified file does not exist", 739},
  {"Upload failed.", 740},
  {"User Menu Editor", 741},
  {"Caption", 742},
  {"Command", 743},
  {"Move Up", 744},
  {"Move Down", 745},
  {"Add", 746},
  {"Save", 747},
  {"Reset", 748},
  {"Edit Entry", 749},
  {"Add Entry", 750},
  {"Type: ", 751},
  {"Caption: ", 752},
  {"Command: ", 753},
  {"Your changes will take effect on next startup", 754},
  {"\
There are unsaved changes to the menu.\n\
\n\
Do you want to save the changes ?", 755},
  {"Don't Quit", 756},
  {"Do you want to delete this entry ?", 757},
  {"\
If you delete a submenu, all its entries and \n\
submenus will also be deleted.\n\
\n\
Do you want to delete this submenu ?", 758},
  {"Item", 759},
  {"Submenu", 760},
  {"Separator", 761},
};

int _msg_tbl_length = 761;
